site_name: Quantum Machine Learning Notes
site_url: https://falak-parmar.github.io/QML-notes/
site_author: Kashyap Sureshchandra Patel, Falak Naresh Parmar
site_description: IT401 â€“ Quantum Machine Learning course notes
repo_name: Falak-Parmar/QML-notes
repo_url: https://github.com/Falak-Parmar/QML-notes
edit_uri: ""

theme:
  name: material
  features:
    - content.tooltips
    - content.tabs.link
    - navigation.instant
    - navigation.instant.progress  
  palette:
    - scheme: default
      toggle: 
        icon: material/weather-sunny
        name: Early Bird

      primary: light blue
      accent: white

    - scheme: slate
      toggle: 
        icon: material/weather-night
        name: Night Owl

      primary: black
      accent: white
      

nav:
  - Home: index.md
  - Course Content: course_content.md
  - Math Prerequisites: math_prerequisites.md

plugins:
  - search
  - social:                 # NEW: Automatically generates social media preview cards
      cards_layout: default/variant 
  - optimize:               # NEW: Compresses and optimizes your images automatically
  - privacy:                # NEW: Self-hosts fonts/assets for GDPR and speed

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css